name: test-harness-ariesvcx-javascript
# RUNSET_NAME: "aries-vcx to javascript"
# Scope: AIP 1.0
# Exceptions: Public Dids
#
# Passing tests: @RFC0036,@RFC0037,@RFC0160,@revocation
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a aries-vcx -a javascript"
          TEST_AGENTS: "-d aries-vcx -b javascript"
          TEST_SCOPE: "-t @RFC0036,@RFC0037,@RFC0160,@revocation -t ~@T005-HIPE0011 -t ~@T006.1-HIPE0011 -t ~@RFC0025 -t ~@RFC0183 -t ~@RFC0211 -t ~@RFC0434 -t ~@RFC0453 -t ~@wip -t ~@DIDExchangeConnection"
          REPORT_PROJECT: aries-vcx-b-javascript
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: agent-logs
          path: ./test-harness/.logs/
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: aries-vcx-b-javascript
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
